const admin = require("firebase-admin");
const path = require("path");
const fs = require("fs");

// Check if service account file exists
const serviceAccountPath = path.join(__dirname, "../config/firebase-service-account.json");
let isInitialized = false;

if (fs.existsSync(serviceAccountPath)) {
    try {
        const serviceAccount = require(serviceAccountPath);
        admin.initializeApp({
            credential: admin.credential.cert(serviceAccount)
        });
        isInitialized = true;
        console.log("[FCM] Firebase Admin initialized using JSON file.");
    } catch (err) {
        console.error("[FCM] Error initializing Firebase Admin from JSON:", err);
    }
} else if (process.env.FIREBASE_PRIVATE_KEY && process.env.FIREBASE_CLIENT_EMAIL) {
    try {
        // Fix for private key newlines in .env
        const privateKey = process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g, '\n').replace(/"/g, '').replace(/,$/, '').trim();
        
        admin.initializeApp({
            credential: admin.credential.cert({
                projectId: process.env.FIREBASE_PROJECT_ID,
                clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
                privateKey: privateKey,
            })
        });
        isInitialized = true;
        console.log("[FCM] Firebase Admin initialized using environment variables.");
    } catch (err) {
        console.error("[FCM] Error initializing Firebase Admin from ENV:", err);
    }
} else {
    console.warn("[FCM] Firebase credentials missing (no JSON file or ENV variables found). Auth will fail.");
}

/**
 * Verify a Firebase ID Token generated by the client
 * @param {string} idToken The Firebase ID token to verify
 * @returns {Promise<object>} The decoded token wrapper
 */
module.exports.verifyFirebaseToken = async (idToken) => {
    if (!isInitialized) {
        throw new Error("Firebase Admin not initialized. Cannot verify token.");
    }
    return await admin.auth().verifyIdToken(idToken);
};


/**
 * Send a push notification to a specific device
 * @param {string} fcmToken The target device's FCM token
 * @param {string} title Notification title
 * @param {string} body Notification body
 * @param {object} data Optional data payload
 */
module.exports.sendPushNotification = async (fcmToken, title, body, data = {}) => {
    if (!isInitialized || !fcmToken) {
        console.log(`[FCM] Skipping push notification (Service not ready or missing token)`);
        return null;
    }

    try {
        const message = {
            notification: {
                title,
                body,
            },
            data: {
                ...data,
                click_action: "FLUTTER_NOTIFICATION_CLICK" // Generic click action for React Native as well
            },
            token: fcmToken,
        };

        const response = await admin.messaging().send(message);
        console.log(`[FCM] Successfully sent push notification:`, response);
        return response;
    } catch (err) {
        console.error(`[FCM] Error sending push notification:`, err);
        return null;
    }
};
